<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>unofficial_pdrive_http_bridge</RootNamespace>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/Proton.Sdk.Drive/Proton.Sdk.Drive.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" Version="9.0.0" />
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
    <PackageReference Include="System.Linq.AsyncEnumerable" Version="10.0.0-preview.7.25380.108" />
    <PackageReference Include="Watson.Lite" Version="6.3.12" />
  </ItemGroup>

</Project>
